### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by GodGun968**
It's good that the untranslated text is automatically filled in. This saves me a lot of work.

### CODE REVIEW

**Comment by hashalite** [comment]
Thank you!

**Comment by hashalite** [comment]
@GodGun968 could you also check out the language file for the modrinth branch? It has a few strings that are different from the main branch. It is available [here](https://github.com/hashalite/Freecam/blob/modrinth-1.19/src/main/resources/assets/freecam/lang/zh_cn.json).

**Comment by GodGun968** [comment]
Oh well, but why don't you just make one language file?

**Comment by hashalite** [comment]
The modrinth version has some strings that are not used in the main version, so it wouldn’t make sense to include them for both.

**Comment by GodGun968** [comment]
Oh, modrinth's mod is a beta right?

**Comment by hashalite** [comment]
What do you mean?

**Comment by GodGun968** [comment]
I mean the version on modrinth is an updated version right?

**Comment by GodGun968** [comment]
my meaning may not be very clear. forget about it, It doesn't have much to do with me.

**Comment by hashalite** [comment]
The version on Modrinth disables noClip, allowInteract, and freezePlayer while in multiplayer in order to comply with Modrinths rules. The main Freecam mod is considered to be a cheat by Modrinth, and cannot be uploaded there.

**Comment by GodGun968** [comment]
Thanks for the explanation, I've got it.

**Comment by hashalite** [comment]
No problem, and I appreciate your work on the translations!

**Comment by GodGun968** [comment]
😊

**Pull request merged**
