### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by GodGun968**
Please also update for other branches

### CODE REVIEW

**Comment by hashalite** [comment]
Thank you! I will merge later today.

**Comment by hashalite** [comment]
Hey, any chance you could check out the new untranslated strings in [zh_cn,json](https://github.com/hashalite/Freecam/blob/main/src/main/resources/assets/freecam/lang/zh_cn.json)?

**Comment by hashalite** [comment]
@GodGun968

**Comment by GodGun968** [comment]
okay, I will soon

**Pull request merged**
